# -*- coding: utf-8 -*-
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary

dokumentarten = SimpleVocabulary(
    [
        SimpleTerm(value=u'unfallanzeige', token=u'unfallanzeige', title=u'Unfallanzeige'),
        SimpleTerm(value=u'd-arzt-bericht', token=u'd-arzt-bericht', title=u'D-Arzt-Bericht'),
        SimpleTerm(value=u'h-arzt-bericht', token=u'h-arzt-bericht', title=u'H-Arzt-Bericht'),
        SimpleTerm(value=u'e-rechnung', token=u'e-rechnung', title=u'E-Rechnung'),
   ]) 

dale = SimpleVocabulary(
    [
        SimpleTerm(value=u'heute', token=u'heute', title=u'heute'),
        SimpleTerm(value=u'vin_1', token=u'vin_1', title=u'Nachname d. Versicherten [vin_1]'),
        SimpleTerm(value=u'vin_2', token=u'vin_2', title=u'Vorname d. Versicherten [vin_2]'),
        SimpleTerm(value=u'vin_3', token=u'vin_3', title=u'StA. Versicherter [vin_3]'),
        SimpleTerm(value=u'vin_4', token=u'vin_4', title=u'Geschlecht d. Versicherten [vin_4]'),
        SimpleTerm(value=u'vin_5', token=u'vin_5', title=u'PLZ d. Versicherten [vin_5]'),
        SimpleTerm(value=u'vin_6', token=u'vin_6', title=u'Ort des Versicherten [vin_6]'),
        SimpleTerm(value=u'vin_7', token=u'vin_7', title=u'Str/Hnr. des Versicherten [vin_7]'),
        SimpleTerm(value=u'vin_8', token=u'vin_8', title=u'Lkz des Wohnortes [vin_8]'),
        SimpleTerm(value=u'vin_9', token=u'vin_9', title=u'Geb.datum des Versicherten [vin_9]'),
        SimpleTerm(value=u'vin_10',token=u'vin_10',title=u'Telefon des Versicherten [vin_10]'),
        SimpleTerm(value=u'vin_11',token=u'vin_11',title=u'Versichertennummer GKV [vin_11]'),
        SimpleTerm(value=u'eti_1', token=u'eti_1', title=u'Eingetroffen am [eti_1]'),
        SimpleTerm(value=u'eti_2', token=u'eti_2', title=u'Eintreffzeit [eti_2]'),
        SimpleTerm(value=u'unb_4', token=u'unb_4', title=u'Erstellungsdatum LE [unb_4]'),
        SimpleTerm(value=u'unb_5', token=u'unb_5', title=u'Uhrzeit der Erstellung [unb_5]'),
        SimpleTerm(value=u'uvt_1', token=u'uvt_1', title=u'Name UVT [uvt_1]'),
        SimpleTerm(value=u'uvt_2', token=u'uvt_2', title=u'IK Nummer UVT [uvt_2]'),
        SimpleTerm(value=u'uvt_3', token=u'uvt_3', title=u'Erstellungsdatum Bericht [uvt_3]'),
        SimpleTerm(value=u'uvt_4', token=u'uvt_4', title=u'Unfalltag [uvt_4]'),
        SimpleTerm(value=u'uvt_5', token=u'uvt_5', title=u'Aktenzeichen des UVT [uvt_5]'),
        SimpleTerm(value=u'ufb_1', token=u'ufb_1', title=u'Firmenname [ufb_1]'),
        SimpleTerm(value=u'ufb_2', token=u'ufb_2', title=u'Lkz des Unfallbetriebes [ufb_2]'),
        SimpleTerm(value=u'ufb_3', token=u'ufb_3', title=u'PLZ des Unfallbetriebes [ufb_3]'),
        SimpleTerm(value=u'ufb_4', token=u'ufb_4', title=u'Ort des Unfallbetriebes [ufb_4]'),
        SimpleTerm(value=u'ufb_5', token=u'ufb_5', title=u'Str/Hnr. Unfallbetrieb [ufb_5]'),
        SimpleTerm(value=u'ufb_6', token=u'ufb_6', title=u'Beschäftigt als [ufb_6]'),
        SimpleTerm(value=u'ufb_7', token=u'ufb_7', title=u'Beschäftigt seit [ufb_7]'),
        SimpleTerm(value=u'ksd_1', token=u'ksd_1', title=u'Krankenkasse Name [ksd_1]'),
        SimpleTerm(value=u'ksd_5', token=u'ksd_5', title=u'Familienversicherung [ksd_5]'),
        SimpleTerm(value=u'ksd_2', token=u'ksd_2', title=u'Krankenkasse IKNr. GKV [ksd_2]'),
        SimpleTerm(value=u'ksd_3', token=u'ksd_3', title=u'Pflegekasse Name [ksd_3]'),
        SimpleTerm(value=u'ksd_4', token=u'ksd_4', title=u'Pflegekasse IK-Nr. [ksd_]'),
        SimpleTerm(value=u'ufd_1', token=u'ufd_1', title=u'Unfallzeit [ufd_1]'),
        SimpleTerm(value=u'ufd_2', token=u'ufd_2', title=u'Arbeitszeit Beginn [ufd_2]'),
        SimpleTerm(value=u'ufd_3', token=u'ufd_3', title=u'Arbeitszeit Ende [ufd_3]'),
        SimpleTerm(value=u'ebh_1', token=u'ebh_1', title=u'Erstbehandlung ab [ebh_1]'),
        SimpleTerm(value=u'ebh_2', token=u'ebh_2', title=u'Erstbehandlung Arzt [ebh_2]'),
        SimpleTerm(value=u'bef_1', token=u'bef_1', title=u'Blutentnahme ja/nein [bef_1]'),
        SimpleTerm(value=u'bef_2', token=u'bef_2', title=u'Alkohol, Drogen, Med. [bef_2]'),
        SimpleTerm(value=u'bef_3', token=u'bef_3', title=u'Anzeichen Sucht-/BTM [bef_3]'),
        SimpleTerm(value=u'dis_1', token=u'dis_1', title=u'Diagnosetext [dis_1]'),
        SimpleTerm(value=u'dis_4', token=u'dis_4', title=u'Diagnoseschlüssel [dis_4]'),
        SimpleTerm(value=u'dis_3', token=u'dis_3', title=u'Diagnosecode [dis_3]'),
        SimpleTerm(value=u'tdh_1', token=u'tdh_1', title=u'Unfallhergang [tdh_1]'),
        SimpleTerm(value=u'tdh_2', token=u'tdh_2', title=u'Unfallverhalten [tdh_2]'),
        SimpleTerm(value=u'tdh_3', token=u'tdh_3', title=u'Befund [tdh_3]'),
        SimpleTerm(value=u'tdh_4', token=u'tdh_4', title=u'Röntgenergebnis [tdh_4]'),
        SimpleTerm(value=u'tdh_5', token=u'tdh_5', title=u'Art der Erstversorgung [tdh_5]'),
        SimpleTerm(value=u'tdh_6', token=u'tdh_6', title=u'Erstversorgung nicht D-Arzt [tdh_6]'),
        SimpleTerm(value=u'tdh_7', token=u'tdh_7', title=u'Unfallabh. Beeinträchtigungen [tdh_7]'),
        SimpleTerm(value=u'bed_1', token=u'bed_1', title=u'Annahme kein Arbeitsunfall [bed_1]'),
        SimpleTerm(value=u'bed_2', token=u'bed_2', title=u'Bedenken zu Arbeitsunfall [bed_2]'),
        SimpleTerm(value=u'beh_1', token=u'beh_1', title=u'Art der Behandlung [beh_1]'),
        SimpleTerm(value=u'beh_15',token=u'beh_15',title=u'keine Behandlung, weil: [beh_15]'),
        SimpleTerm(value=u'beh_2', token=u'beh_2', title=u'Behandlungstyp [beh_2]'),
        SimpleTerm(value=u'beh_3', token=u'beh_3', title=u'Behandlung durch [beh_3]'),
        SimpleTerm(value=u'beh_4', token=u'beh_4', title=u'Verletzung nach VAV [beh_4]'),
        SimpleTerm(value=u'beh_5', token=u'beh_5', title=u'Ziffer des VAV-Kataloges [beh_5]'),
        SimpleTerm(value=u'beh_6', token=u'beh_6', title=u'Nachschau am: (Datum) [beh_6]'),
        SimpleTerm(value=u'beh_7', token=u'beh_7', title=u'Weiterb. Praxis/KKH  [beh_7]'),
        SimpleTerm(value=u'beh_8', token=u'beh_8', title=u'Praxis/KKH Str/Hnr [beh_8]'),
        SimpleTerm(value=u'beh_9', token=u'beh_9', title=u'Praxis/KKH PLZ [beh_9]'),
        SimpleTerm(value=u'beh_10',token=u'beh_10',title=u'Praxis/KKH Ort [beh_10]'),
        SimpleTerm(value=u'beh_11',token=u'beh_11',title=u'Praxis/KKH LKZ [beh_11]'),
        SimpleTerm(value=u'beh_14',token=u'beh_14',title=u'Weiterl. an Arzt/KKH [beh_14]'),
        SimpleTerm(value=u'afb_1', token=u'afb_1', title=u'Arbeitsfähig [afb_1]'),
        SimpleTerm(value=u'afb_4', token=u'afb_4', title=u'Arbeitunfähig ab [afb_4]'),
        SimpleTerm(value=u'afb_7', token=u'afb_7', title=u'vrs. arbeitsfähig ab [afb_7]'),
        SimpleTerm(value=u'afb_8', token=u'afb_8', title=u'vrs. Dauer über 6 Monate [afb_8]'),
        SimpleTerm(value=u'ber_1', token=u'ber_1', title=u'Beratung durch UVT [ber_1]'),
        SimpleTerm(value=u'ber_2', token=u'ber_2', title=u'Beratung weil: [ber_2]'),
        SimpleTerm(value=u'kon_1', token=u'kon_1', title=u'Konsiliararzt ja/nein [kon_1]'),
        SimpleTerm(value=u'kon_2', token=u'kon_2', title=u'Name des Konsiliararztes [kon_2]'),
        SimpleTerm(value=u'kon_3', token=u'kon_3', title=u'Str/Hnr. d. Konsiliararztes [kon_3]'),
        SimpleTerm(value=u'kon_4', token=u'kon_4', title=u'PLZ des Konsiliararztes [kon_4]'),
        SimpleTerm(value=u'kon_5', token=u'kon_5', title=u'Ort des Konsiliararztes [kon_5]'),
        SimpleTerm(value=u'kon_6', token=u'kon_6', title=u'LKZ des Konsiliararztes [kon_6]'),
        SimpleTerm(value=u'kon_7', token=u'kon_7', title=u'Weiterl. an Konsiliararzt [kon_7]'),
        SimpleTerm(value=u'sri_1', token=u'sri_1', title=u'Art der Heilbehandlung [sri_1]'),
        SimpleTerm(value=u'sri_2', token=u'sri_2', title=u'Rechnungstyp [sri_2]'),
        SimpleTerm(value=u'sri_3', token=u'sri_3', title=u'Ost-Abschlag [sri_3]'),
        SimpleTerm(value=u'sri_4', token=u'sri_4', title=u'Summe Gebühr [sri_4]'),
        SimpleTerm(value=u'sri_5', token=u'sri_5', title=u'Summe Besondere Kosten [sri_5]'),
        SimpleTerm(value=u'sri_6', token=u'sri_6', title=u'Summe Allgemeine Kosten [sri_6]'),
        SimpleTerm(value=u'sri_7', token=u'sri_7', title=u'Summe Sachkosten [sri_7]'),
        SimpleTerm(value=u'rel_1', token=u'rel_1', title=u'Leistungsdatum [rel_1]'),
        SimpleTerm(value=u'rel_2', token=u'rel_2', title=u'Gebühr [rel_2]'),
        SimpleTerm(value=u'rel_3', token=u'rel_3', title=u'Leistungsposition [rel_3]'),
        SimpleTerm(value=u'rel_4', token=u'rel_4', title=u'Leistungsposition Schlüssel [rel_4]'),
        SimpleTerm(value=u'rel_5', token=u'rel_5', title=u'Besondere Kosten [rel_5]'),
        SimpleTerm(value=u'rel_6', token=u'rel_6', title=u'Allgemeine Kosten [rel_6]'),
        SimpleTerm(value=u'rel_7', token=u'rel_7', title=u'Sachkosten Kosten [rel_7]'),
        SimpleTerm(value=u'rel_8', token=u'rel_8', title=u'Bemerkungen [rel_8]'),
        SimpleTerm(value=u'kto_1', token=u'kto_1', title=u'Gesamtbetrag [kto_1]'),
        SimpleTerm(value=u'kto_2', token=u'kto_2', title=u'Rechnungsnummer [kto_2]'),
        SimpleTerm(value=u'kto_3', token=u'kto_3', title=u'IK des Zahlungsempfängers [kto_3]'),
        SimpleTerm(value=u'abs_1', token=u'abs_1', title=u'Absendername [abs_1]'),
        SimpleTerm(value=u'abs_2', token=u'abs_2', title=u'Str./Hnr. des Absenders [abs_2]'),
        SimpleTerm(value=u'abs_3', token=u'abs_3', title=u'PLZ des Absenders [abs_3]'),
        SimpleTerm(value=u'abs_4', token=u'abs_4', title=u'Ort des Absenders [abs_4]'),
        SimpleTerm(value=u'abs_5', token=u'abs_5', title=u'LKZ des Absenders [abs_5]'),
        SimpleTerm(value=u'abs_6', token=u'abs_6', title=u'Telefon des Absenders [abs_6]'),
        SimpleTerm(value=u'abs_7', token=u'abs_7', title=u'Ansp. des Absenders [abs_7]'),
        SimpleTerm(value=u'not_1', token=u'not_1', title=u'Notiz [not_1]'),
        SimpleTerm(value=u'swh_1', token=u'swh_1', title=u'Softwarename [swh_1]'),
        SimpleTerm(value=u'swh_2', token=u'swh_2', title=u'Name des SW-Moduls [swh_2]'),
        SimpleTerm(value=u'swi_1', token=u'swi_1', title=u'Felderkennung [swh_1]'),
        SimpleTerm(value=u'swi_2', token=u'swi_2', title=u'Feldinhalt [swh_2]')
        ])
