# -*- coding: utf-8 -*-
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary

dokumentarten = SimpleVocabulary(
    [
        SimpleTerm(value=u'unfallanzeige', token=u'unfallanzeige', title=u'Unfallanzeige'),
        SimpleTerm(value=u'd-arzt-bericht', token=u'd-arzt-bericht', title=u'D-Arzt-Bericht'),
        SimpleTerm(value=u'h-arzt-bericht', token=u'h-arzt-bericht', title=u'H-Arzt-Bericht'),
   ]) 

dale = SimpleVocabulary(
    [
        SimpleTerm(value=u'heute', token=u'heute', title=u'heute'),
        SimpleTerm(value=u'vin_1', token=u'vin_1', title=u'Nachname d. Versicherten'),
        SimpleTerm(value=u'vin_2', token=u'vin_2', title=u'Vorname d. Versicherten'),
        SimpleTerm(value=u'vin_3', token=u'vin_3', title=u'Staatsangehörigkeit Versicherter'),
        SimpleTerm(value=u'vin_4', token=u'vin_4', title=u'Geschlecht des Versicherten'),
        SimpleTerm(value=u'vin_5', token=u'vin_5', title=u'Postleitzahl des Versicherten'),
        SimpleTerm(value=u'vin_6', token=u'vin_6', title=u'Ort des Versicherten'),
        SimpleTerm(value=u'vin_7', token=u'vin_7', title=u'Straße/Hausnr. des Versicherten'),
        SimpleTerm(value=u'vin_8', token=u'vin_8', title=u'Länderkennzeichen des Wohnortes'),
        SimpleTerm(value=u'vin_9', token=u'vin_9', title=u'Geburtsdatum des Versicherten'),
        SimpleTerm(value=u'vin_10',token=u'vin_10',title=u'Telefon des Versicherten'),
        SimpleTerm(value=u'vin_11',token=u'vin_11',title=u'Versichertennummer GKV'),
        SimpleTerm(value=u'eti_1', token=u'eti_1', title=u'Eingetroffen am'),
        SimpleTerm(value=u'eti_2', token=u'eti_2', title=u'Eintreffzeit'),
        SimpleTerm(value=u'unb_4', token=u'unb_4', title=u'Erstellungsdatum Leistungserbringer'),
        SimpleTerm(value=u'unb_5', token=u'unb_5', title=u'Uhrzeit der Erstellung'),
        SimpleTerm(value=u'uvt_1', token=u'uvt_1', title=u'Name UVT'),
        SimpleTerm(value=u'uvt_2', token=u'uvt_2', title=u'IK Nummer UVT'),
        SimpleTerm(value=u'uvt_3', token=u'uvt_3', title=u'Erstellungsdatum des Berichtes'),
        SimpleTerm(value=u'uvt_4', token=u'uvt_4', title=u'Unfalltag'),
        SimpleTerm(value=u'uvt_5', token=u'uvt_5', title=u'Aktenzeichen des UVT'),
        SimpleTerm(value=u'ufb_1', token=u'ufb_1', title=u'Firmenname'),
        SimpleTerm(value=u'ufb_2', token=u'ufb_2', title=u'Lkz des Unfallbetriebes'),
        SimpleTerm(value=u'ufb_3', token=u'ufb_3', title=u'PLZ des Unfallbetriebes'),
        SimpleTerm(value=u'ufb_4', token=u'ufb_4', title=u'Ort des Unfallbetriebes'),
        SimpleTerm(value=u'ufb_5', token=u'ufb_5', title=u'Straße/Hausnr. des Unfallbetriebes'),
        SimpleTerm(value=u'ufb_6', token=u'ufb_6', title=u'Beschäftigt als'),
        SimpleTerm(value=u'ufb_7', token=u'ufb_7', title=u'Beschäftigt seit'),
        SimpleTerm(value=u'ksd_1', token=u'ksd_1', title=u'Krankenkasse Name'),
        SimpleTerm(value=u'ksd_5', token=u'ksd_5', title=u'Familienversicherung'),
        SimpleTerm(value=u'ksd_2', token=u'ksd_2', title=u'Krankenkasse IK-Nr.Nur bei GKV'),
        SimpleTerm(value=u'ksd_3', token=u'ksd_3', title=u'Pflegekasse Name'),
        SimpleTerm(value=u'ksd_4', token=u'ksd_4', title=u'Pflegekasse IK-Nr.'),
        SimpleTerm(value=u'ufd_1', token=u'ufd_1', title=u'Unfallzeit'),
        SimpleTerm(value=u'ufd_2', token=u'ufd_2', title=u'Arbeitszeit Beginn'),
        SimpleTerm(value=u'ufd_3', token=u'ufd_3', title=u'Arbeitszeit Ende'),
        SimpleTerm(value=u'ebh_1', token=u'ebh_1', title=u'Erstbehandlung ab'),
        SimpleTerm(value=u'ebh_2', token=u'ebh_2', title=u'Erstbehandlung Arzt'),
        SimpleTerm(value=u'bef_1', token=u'bef_1', title=u'Blutentnahme ja/nein'),
        SimpleTerm(value=u'bef_2', token=u'bef_2', title=u'Alkohol, Drogen, Medikamente'),
        SimpleTerm(value=u'bef_3', token=u'bef_3', title=u'Anzeichen Sucht-/Betäubungsmittel'),
        SimpleTerm(value=u'dis_1', token=u'dis_1', title=u'Diagnosetext'),
        SimpleTerm(value=u'dis_4', token=u'dis_4', title=u'Diagnoseschlüssel'),
        SimpleTerm(value=u'dis_3', token=u'dis_3', title=u'Diagnosecode'),
        SimpleTerm(value=u'tdh_1', token=u'tdh_1', title=u'Unfallhergang'),
        SimpleTerm(value=u'tdh_2', token=u'tdh_2', title=u'Unfallverhalten'),
        SimpleTerm(value=u'tdh_3', token=u'tdh_3', title=u'Befund'),
        SimpleTerm(value=u'tdh_4', token=u'tdh_4', title=u'Röntgenergebnis'),
        SimpleTerm(value=u'tdh_5', token=u'tdh_5', title=u'Art der Erstversorgung'),
        SimpleTerm(value=u'tdh_6', token=u'tdh_6', title=u'??'),
        SimpleTerm(value=u'tdh_7', token=u'tdh_7', title=u'Unfallabh. Beeinträchtigungen'),
        SimpleTerm(value=u'bed_1', token=u'bed_1', title=u'Annahme kein Arbeitsunfall'),
        SimpleTerm(value=u'bed_2', token=u'bed_2', title=u'Bedenken zu Arbeitsunfall'),
        SimpleTerm(value=u'beh_1', token=u'beh_1', title=u'Art der Behandlung'),
        SimpleTerm(value=u'beh_15',token=u'beh_15',title=u'keine Behandlung, weil:'),
        SimpleTerm(value=u'beh_2', token=u'beh_2', title=u'Behandlungstyp'),
        SimpleTerm(value=u'beh_3', token=u'beh_3', title=u'Behandlung durch'),
        SimpleTerm(value=u'beh_4', token=u'beh_4', title=u'Verletzung nach VAV'),
        SimpleTerm(value=u'beh_5', token=u'beh_5', title=u'Ziffer des VAV-Kataloges'),
        SimpleTerm(value=u'beh_6', token=u'beh_6', title=u'Nachschau am: (Datum)'),
        SimpleTerm(value=u'beh_7', token=u'beh_7', title=u'Weiterbehandelnde Praxis/KKH '),
        SimpleTerm(value=u'beh_8', token=u'beh_8', title=u'Praxis/KKH Str/Hnr'),
        SimpleTerm(value=u'beh_9', token=u'beh_9', title=u'Praxis/KKH PLZ'),
        SimpleTerm(value=u'beh_10',token=u'beh_10',title=u'Praxis/KKH Ort'),
        SimpleTerm(value=u'beh_11',token=u'beh_11',title=u'Praxis/KKH LKZ'),
        SimpleTerm(value=u'beh_14',token=u'beh_14',title=u'Weiterleitung an Arzt/KKH'),
        SimpleTerm(value=u'afb_1', token=u'afb_1', title=u'Arbeitsfähig'),
        SimpleTerm(value=u'afb_4', token=u'afb_4', title=u'Arbeitunfähig ab'),
        SimpleTerm(value=u'afb_7', token=u'afb_7', title=u'Vorauss. wieder arbeitsfähig ab'),
        SimpleTerm(value=u'afb_8', token=u'afb_8', title=u'Vorauss. Dauer über 6 Monate'),
        SimpleTerm(value=u'ber_1', token=u'ber_1', title=u'Beratung durch UVT erforderlich'),
        SimpleTerm(value=u'ber_2', token=u'ber_2', title=u'Beratung weil'),
        SimpleTerm(value=u'kon_1', token=u'kon_1', title=u'Hinzuziehung Konsiliararztes'),
        SimpleTerm(value=u'kon_2', token=u'kon_2', title=u'Name des Konsiliararztes'),
        SimpleTerm(value=u'kon_3', token=u'kon_3', title=u'Str/Hnr. des Konsiliararztes'),
        SimpleTerm(value=u'kon_4', token=u'kon_4', title=u'PLZ des Konsiliararztes'),
        SimpleTerm(value=u'kon_5', token=u'kon_5', title=u'Ort des Konsiliararztes'),
        SimpleTerm(value=u'kon_6', token=u'kon_6', title=u'LKZ des Konsiliararztes'),
        SimpleTerm(value=u'kon_7', token=u'kon_7', title=u'Weiterleitung an Konsiliararzt'),
        SimpleTerm(value=u'sri_1', token=u'sri_1', title=u'Art der Heilbehandlung'),
        SimpleTerm(value=u'sri_2', token=u'sri_2', title=u'Rechnungstyp'),
        SimpleTerm(value=u'sri_3', token=u'sri_3', title=u'Ost-Abschlag'),
        SimpleTerm(value=u'sri_4', token=u'sri_4', title=u'Summe Gebühr'),
        SimpleTerm(value=u'sri_5', token=u'sri_5', title=u'Summe Besondere Kosten'),
        SimpleTerm(value=u'sri_6', token=u'sri_6', title=u'Summe Allgemeine Kosten'),
        SimpleTerm(value=u'sri_7', token=u'sri_7', title=u'Summe Sachkosten'),
        SimpleTerm(value=u'rel_1', token=u'rel_1', title=u'Leistungsdatum'),
        SimpleTerm(value=u'rel_2', token=u'rel_2', title=u'Gebühr'),
        SimpleTerm(value=u'rel_3', token=u'rel_3', title=u'Leistungsposition'),
        SimpleTerm(value=u'rel_4', token=u'rel_4', title=u'Leistungsposition Schlüssel'),
        SimpleTerm(value=u'rel_5', token=u'rel_5', title=u'Besondere Kosten'),
        SimpleTerm(value=u'rel_6', token=u'rel_6', title=u'Allgemeine Kosten'),
        SimpleTerm(value=u'rel_7', token=u'rel_7', title=u'Sachkosten Kosten'),
        SimpleTerm(value=u'rel_8', token=u'rel_8', title=u'Bemerkungen'),
        SimpleTerm(value=u'kto_1', token=u'kto_1', title=u'Gesamtbetrag'),
        SimpleTerm(value=u'kto_2', token=u'kto_2', title=u'Rechnungsnummer'),
        SimpleTerm(value=u'kto_3', token=u'kto_3', title=u'IK des Zahlungsempfängers'),
        SimpleTerm(value=u'abs_1', token=u'abs_1', title=u'Absendername'),
        SimpleTerm(value=u'abs_2', token=u'abs_2', title=u'Straße und Nr. des Absenders'),
        SimpleTerm(value=u'abs_3', token=u'abs_3', title=u'PLZ des Absenders'),
        SimpleTerm(value=u'abs_4', token=u'abs_4', title=u'Ort des Absenders'),
        SimpleTerm(value=u'abs_5', token=u'abs_5', title=u'LKZ des Absenders'),
        SimpleTerm(value=u'abs_6', token=u'abs_6', title=u'Telefon des Absenders'),
        SimpleTerm(value=u'abs_7', token=u'abs_7', title=u'Ansprechpartner des Absenders'),
        SimpleTerm(value=u'not_1', token=u'not_1', title=u'Notiz'),
        SimpleTerm(value=u'swh_1', token=u'swh_1', title=u'Softwarename'),
        SimpleTerm(value=u'swh_2', token=u'swh_2', title=u'Name des eingesetzten Moduls'),
        SimpleTerm(value=u'swi_1', token=u'swi_1', title=u'Felderkennung'),
        SimpleTerm(value=u'swi_2', token=u'swi_2', title=u'Feldinhalt')
        ])
